### PR TITLE
JournalStoreVsJdbcStoreOnlineTest fix

### PR DESCRIPTION
**Pull request by ChesterSVK**
Fix for issue: https://github.com/wildfly-extras/creaper/issues/166 

Use-journal-store and use-jdbc-store attributes must be set exclusively and server must be restarted for avoiding this conflict.

### CODE REVIEW

**Comment by olukas** [comment]
+1 for check in builder whether only one of journal store and JDBC store is configured. However I think that disabling JDBC when enabling journal and vice versa can cause some tricky issues for users - e.g. in case when they accidentally try to configure both store - in that case I believe that just thrown Exception is better than use last configured value for store.

@ChesterSVK As I said in https://github.com/wildfly-extras/creaper/issues/166 - `ChangeJdbcAttributesOnlineTest` and `ChangeBasicAttributesOnlineTest` intermittently fail with the same failure-description. Could you please fix also those test cases as part of this PR?

**Comment by Ladicek** [comment]
> However I think that disabling JDBC when enabling journal and vice versa can cause some tricky issues for users

Yea, should probably just document that WildFly changed behavior in this.

**Comment by olukas** [comment]
@ChesterSVK Hi, is there any progress with fixing `ChangeJdbcAttributesOnlineTest` and `ChangeBasicAttributesOnlineTest` please?

**Comment by rsvoboda** [comment]
@msve please take a look

@Ladicek can you grant rights for creaper repo to @msve ?
He is "component owner" now on eap qe side.

**Pull request merged**
