### PR TITLE
Added ATTRIBUTES_ONLY to ReadResourceOption

### PR DESCRIPTION
**Pull request by honza-kasik**

### CODE REVIEW

**Comment by Ladicek** [comment]
LGTM. Can you add a test?

**Comment by honza-kasik** [comment]
Added a test...

**Comment by Ladicek** [comment]
Please rebase on current master and squash.

**Comment by honza-kasik** [comment]
Rebased and squashed.

**Comment by Ladicek** [comment]
Hmm, this doesn't build on Java 6 (i.e., with EAP 6 version of the DMR library). The `hasDefined(String...)` method doesn't exist there. Maybe the assertion could be simplified a bit?

**Comment by Ladicek** [comment]
I'd suggest something like this for the test:

```java
ModelNodeResult result = ops.readResource(Address.subsystem(webSubsystem), ReadResourceOption.ATTRIBUTES_ONLY);
result.assertDefinedValue();
assertFalse(result.hasDefined("configuration"));
```

WDYT?

**Comment by honza-kasik** [comment]
Sorry, I shall test it properly next time, I forgot about other versions... Test simplified and squashed.

**Pull request merged**
