### PR TITLE
Support mcp attribute with data sources

### PR DESCRIPTION
**Pull request by jmartisk**

### CODE REVIEW

**Comment by Ladicek** [comment]
Looks good. Is it easy to add a test (or rather modify an existing one), or would that be too scary?

**Comment by ochaloup** [comment]
And maybe it would be have this for offline command as well.

**Comment by Ladicek** [comment]
+1, I think that generally online and offline variants should be symmetric.

**Comment by jmartisk** [comment]
Fixed.

**Comment by Ladicek** [comment]
What's that commit message? :-) Otherwise, LGTM.

**Comment by jmartisk** [comment]
Fixed the 'fixed' keyword :)

**Comment by Ladicek** [comment]
Thanks!

**Pull request merged**
