### PR TITLE
update travis config to use openjdk8

### PR DESCRIPTION
**Pull request by ctomc**

### CODE REVIEW

**Comment by simkam** [comment]
there is old PR with fix for JournalStoreVsJdbcStoreOnlineTest -  https://github.com/wildfly-extras/creaper/pull/169

**Comment by Ladicek** [comment]
Ah, good point. Well, clearly someone needs to start taking care of Creaper again :-)

**Comment by rsvoboda** [comment]
@ctomc @Ladicek I will bring this topic to the proper guys ;)

**Comment by rsvoboda** [comment]
@msve please take a look

@Ladicek can you grant rights for creaper repo to @msve ?
He is "component owner" now on eap qe side.

**Comment by Ladicek** [comment]
Invite sent.

**Pull request merged**
