### PR TITLE
add Administration.shutdownGracefully

### LINKED ISSUE #125: add Administration.shutdownGracefully
Will have to throw an exception if the server doesn't support graceful shutdown.

Related to #120.

### PR DESCRIPTION
**Pull request by Ladicek**
Fixes #125.

### CODE REVIEW

**Comment by Ladicek** [comment]
I'm currently not sure if this is a proper way of supporting graceful shutdown in Creaper, so I'm going to leave the pull request open for some time for review.

CC @rhatlapa.

**Comment by rhatlapa** [comment]
LGTM, maybe also some tests might be added, mainly some tests which would make sure it doesn't get broken for the older versions of the WildFly/AS7 servers (no-one will remove or forget to have proper handling for `timeout=0` (currently seems done properly, having test for it would give better guarantees :-)).

**Comment by Ladicek** [comment]
Tests are definitely missing, thanks for the notice.

**Comment by Ladicek** [comment]
Added a test. The new commits are supposed to be squashed.

**Comment by rhatlapa** [comment]
Thanks, LGTM.

**Pull request merged**
