### PR TITLE
Add Travis CI configuration for creaper

### PR DESCRIPTION
**Pull request by kwart**
This also requires enabling access to the repository in the Travis CI. 

https://travis-ci.org/profile/wildfly-extras

@Ladicek Could you enable it?

### CODE REVIEW

**Comment by Ladicek** [comment]
What is it going to do? I'd like `mvn clean verify`.

**Comment by kwart** [comment]
https://docs.travis-ci.com/user/languages/java

We can specify steps, by default it does
```
mvn test
```

and before running the build, Travis CI installs dependencies:
```
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
```

**Comment by kwart** [comment]
Are there any integration tests, so the `verify` is required? Or do we have just unit tests and the `test` phase is enough?

**Comment by Ladicek** [comment]
OK, my Travis skill is zero, could you please make it do `verify`? Static checks are done in that phase (CheckStyle, Findbugs, CodeNarc).

**Comment by kwart** [comment]
Updated.

**Comment by Ladicek** [comment]
OK, thanks. Looks reasonable, not sure how to test it other than merging this :-)

**Pull request merged**
