### PR TITLE
Allow defining security realm without truststore

### LINKED ISSUE #49: Security realm command should allow defining realm without truststore
Not always user wants to use both side ssl authentication and wants to define only keystore with server certificate.

### PR DESCRIPTION
**Pull request by rhatlapa**
based on whether truststorePath is provided decides whether also add truststore or not. Test included.

fixes #49

### CODE REVIEW

**Comment by Ladicek** [comment]
LGTM. Could you please consider my suggestion in #49?

**Comment by rhatlapa** [comment]
I have added improved check for mandatory parameters and improved javadoc

I have also added to .gitignore ignoring of log files to ignore mainly server.log created when running tests.

**Comment by rhatlapa** [comment]
please review again :-)

**Comment by Ladicek** [comment]
Thanks! LGTM, I'll merge.

**Pull request merged**
