### PR TITLE
Updating vulnurable dependencies reported by Snyk.io

### PR DESCRIPTION
**Pull request by istraka**
New dependencies have introduced new rules for find bugs plugin -> issues are fixed

### CODE REVIEW

**Comment by rsvoboda** [comment]
@msve please take a look

@Ladicek can you grant rights for creaper repo to @msve ?
He is "component owner" now on eap qe side.

**Comment by simkam** [comment]
@istraka please rebase

**Comment by istraka** [comment]
@simkam done

**Comment by simkam** [comment]
I'm adding label 2.0. Guava requires JDK8 starting with v21.

**Comment by jstourac** [comment]
I believe this PR is outdated and should be closed:

1. Both changes in `pom.xml` file are irrelevant already (newer versions are used in master now).
2. Changes regarding the store closing - according the documentation the method [Closeables.closeQuietly(InputStream)](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/io/Closeables.html#closeQuietly(java.io.InputStream)) accepts `null` and does nothing in such case so provided changes doesn't make sense to me anyway.

**Pull request closed without merging**
