### PR TITLE
Log creaper commands in JSON format in debug

### LINKED ISSUE #151: Log details of creaper commands
Here is the idea. Enable TRACE logging of commands, by extending OperationsModelNodeBuilder with logging of op.toJSONString(false).
`{
    "operation" : "add",
    "address" : [
        {
            "subsystem" : "elytron"
        },
        {
            "key-store" : "CreaperTestKeyStore"
        }
    ],
    "name" : "CreaperTestKeyStore",
    "type" : "JKS",
    "credential-reference" : {"clear-text" : "password"}
}`

Sometimes it come useful to see exactly what is going on in server configuration. Also this output could be used to build reproducers. Copy output from log and pass it to 
`
curl --digest -L -D - http://localhost:9990/management -u admin:asdasd --header "Content-Type: application/json"  -d '{"operation":"reload","name":"", "address":{"host" : "master"},"json.pretty":1}' 
`
Now I only get:
`INFO: Applying command org.wildfly.extras.creaper.commands.elytron.tls.AddKeyStore@7d3d101b`

@Ladicek , WDYT?

### PR DESCRIPTION
**Pull request by mchoma**
Resolves #151

It producelog output as:
INFO: Executing operation /core-service=management/security-realm=creaperSecRealm:add
JSON format:
{
"operation" : "add",
"address" : [
{
"core-service" : "management"
},
{
"security-realm" : "creaperSecRealm"
}
]
}

### CODE REVIEW

**Comment by mchoma** [comment]
following https://github.com/wildfly-extras/creaper/pull/153

**Comment by Ladicek** [comment]
You could have just adjusted #153, but whatever works for you :-)

**Comment by Ladicek** [comment]
Now looking at the 1st comment -- is the JSON format really multiline?

**Comment by mchoma** [comment]
Not sure, if I understand you correctly. When toJSONString(compact=false) is called, then yes operation is printed "nicely" on multiple lines.

**Comment by Ladicek** [comment]
Ah, I definitely don't want that on DEBUG level. That would be too much of a change. And if I remember correctly, you wanted that JSON for pasting into a `curl` invocation, so you should rather want a compact output, no?

**Comment by mchoma** [comment]
Ok. I will add then own TRACE level log entry for JSON format. I prefer compact=false, as it is more human-readable and curl is OK with it.

**Comment by Ladicek** [comment]
Ah, OK, thanks.

**Comment by Ladicek** [comment]
Oh crap, I shouldn't have merged just yet :-( What's the difference between

```java
log.tracef("JSON format:\n%s", operation.toJSONString(false));
```

and

```java
log.tracef("JSON format:%n%s", operation.getOperation().toJSONString(false));
```

?

Specifically, I'm thinking about `\n` vs. `%n`.

Which one is correct?

**Comment by Ladicek** [comment]
@mchoma bump

**Comment by mchoma** [comment]
%n is correct, because it is platform independent.

Should I send new PR with only that change?

**Comment by rhatlapa** [comment]
Yes please.

**Comment by Ladicek** [comment]
Absolutely, thanks.

**Pull request merged**
